// Generated by Supabase CLI — run: supabase gen types typescript --linked > src/lib/database.types.ts
// This is a placeholder until the migrations are applied and types are generated.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export type Database = {
  public: {
    Tables: {
      agents: {
        Row: {
          id: string;
          slug: string;
          name: string;
          type: string;
          status: string;
          model: string;
          workspace_path: string | null;
          notes: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          slug: string;
          name: string;
          type: string;
          status: string;
          model: string;
          workspace_path?: string | null;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          slug?: string;
          name?: string;
          type?: string;
          status?: string;
          model?: string;
          workspace_path?: string | null;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      agent_reports: {
        Row: {
          id: string;
          agent_id: string;
          report_type: string;
          content: Json;
          flagged: boolean;
          flag_level: string | null;
          related_entity_type: string | null;
          related_entity_id: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          agent_id: string;
          report_type: string;
          content: Json;
          flagged?: boolean;
          flag_level?: string | null;
          related_entity_type?: string | null;
          related_entity_id?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          agent_id?: string;
          report_type?: string;
          content?: Json;
          flagged?: boolean;
          flag_level?: string | null;
          related_entity_type?: string | null;
          related_entity_id?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
      agent_logs: {
        Row: {
          id: string;
          agent_id: string;
          action: string;
          detail: string | null;
          related_entity_type: string | null;
          related_entity_id: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          agent_id: string;
          action: string;
          detail?: string | null;
          related_entity_type?: string | null;
          related_entity_id?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          agent_id?: string;
          action?: string;
          detail?: string | null;
          related_entity_type?: string | null;
          related_entity_id?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
      leads: {
        Row: {
          id: string;
          company_name: string;
          contact_name: string | null;
          contact_role: string | null;
          source: string | null;
          sector: string | null;
          country: string;
          stage: string;
          qualified: boolean | null;
          disqualified_reason: string | null;
          sdr_brief: Json | null;
          meddic: Json | null;
          assigned_agent_id: string | null;
          last_activity_at: string | null;
          stall_flagged: boolean;
          created_at: string;
          updated_at: string;
          archived_at: string | null;
        };
        Insert: {
          id?: string;
          company_name: string;
          contact_name?: string | null;
          contact_role?: string | null;
          source?: string | null;
          sector?: string | null;
          country?: string;
          stage: string;
          qualified?: boolean | null;
          disqualified_reason?: string | null;
          sdr_brief?: Json | null;
          meddic?: Json | null;
          assigned_agent_id?: string | null;
          last_activity_at?: string | null;
          stall_flagged?: boolean;
          created_at?: string;
          updated_at?: string;
          archived_at?: string | null;
        };
        Update: {
          id?: string;
          company_name?: string;
          contact_name?: string | null;
          contact_role?: string | null;
          source?: string | null;
          sector?: string | null;
          country?: string;
          stage?: string;
          qualified?: boolean | null;
          disqualified_reason?: string | null;
          sdr_brief?: Json | null;
          meddic?: Json | null;
          assigned_agent_id?: string | null;
          last_activity_at?: string | null;
          stall_flagged?: boolean;
          created_at?: string;
          updated_at?: string;
          archived_at?: string | null;
        };
        Relationships: [];
      };
      lead_stage_history: {
        Row: {
          id: string;
          lead_id: string;
          from_stage: string | null;
          to_stage: string;
          changed_by_agent_id: string | null;
          note: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          lead_id: string;
          from_stage?: string | null;
          to_stage: string;
          changed_by_agent_id?: string | null;
          note?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          lead_id?: string;
          from_stage?: string | null;
          to_stage?: string;
          changed_by_agent_id?: string | null;
          note?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
      proposals: {
        Row: {
          id: string;
          lead_id: string;
          version: number;
          status: string;
          value: number | null;
          monthly_value: number | null;
          payment_terms: string;
          scope_summary: string | null;
          gate_atlas_required: boolean;
          gate_atlas_cleared: boolean;
          gate_atlas_cleared_at: string | null;
          gate_legal_cleared: boolean;
          gate_legal_cleared_at: string | null;
          gate_legal_notes: string | null;
          gate_finance_cleared: boolean;
          gate_finance_cleared_at: string | null;
          gate_finance_notes: string | null;
          boss_approved: boolean;
          boss_approved_at: string | null;
          sent_at: string | null;
          follow_up_48h_sent: boolean;
          follow_up_5d_sent: boolean;
          follow_up_10d_sent: boolean;
          outcome: string | null;
          outcome_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          lead_id: string;
          version?: number;
          status: string;
          value?: number | null;
          monthly_value?: number | null;
          payment_terms?: string;
          scope_summary?: string | null;
          gate_atlas_required?: boolean;
          gate_atlas_cleared?: boolean;
          gate_atlas_cleared_at?: string | null;
          gate_legal_cleared?: boolean;
          gate_legal_cleared_at?: string | null;
          gate_legal_notes?: string | null;
          gate_finance_cleared?: boolean;
          gate_finance_cleared_at?: string | null;
          gate_finance_notes?: string | null;
          boss_approved?: boolean;
          boss_approved_at?: string | null;
          sent_at?: string | null;
          follow_up_48h_sent?: boolean;
          follow_up_5d_sent?: boolean;
          follow_up_10d_sent?: boolean;
          outcome?: string | null;
          outcome_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          lead_id?: string;
          version?: number;
          status?: string;
          value?: number | null;
          monthly_value?: number | null;
          payment_terms?: string;
          scope_summary?: string | null;
          gate_atlas_required?: boolean;
          gate_atlas_cleared?: boolean;
          gate_atlas_cleared_at?: string | null;
          gate_legal_cleared?: boolean;
          gate_legal_cleared_at?: string | null;
          gate_legal_notes?: string | null;
          gate_finance_cleared?: boolean;
          gate_finance_cleared_at?: string | null;
          gate_finance_notes?: string | null;
          boss_approved?: boolean;
          boss_approved_at?: string | null;
          sent_at?: string | null;
          follow_up_48h_sent?: boolean;
          follow_up_5d_sent?: boolean;
          follow_up_10d_sent?: boolean;
          outcome?: string | null;
          outcome_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      clients: {
        Row: {
          id: string;
          lead_id: string | null;
          proposal_id: string | null;
          company_name: string;
          contact_name: string | null;
          contact_email: string | null;
          sector: string | null;
          country: string | null;
          contract_start: string;
          contract_end: string;
          monthly_value: number;
          health_status: string;
          onboarding_complete: boolean;
          onboarding_completed_at: string | null;
          renewal_flagged_90d: boolean;
          renewal_flagged_30d: boolean;
          assigned_am_id: string | null;
          created_at: string;
          updated_at: string;
          archived_at: string | null;
        };
        Insert: {
          id?: string;
          lead_id?: string | null;
          proposal_id?: string | null;
          company_name: string;
          contact_name?: string | null;
          contact_email?: string | null;
          sector?: string | null;
          country?: string | null;
          contract_start: string;
          contract_end: string;
          monthly_value: number;
          health_status?: string;
          onboarding_complete?: boolean;
          onboarding_completed_at?: string | null;
          renewal_flagged_90d?: boolean;
          renewal_flagged_30d?: boolean;
          assigned_am_id?: string | null;
          created_at?: string;
          updated_at?: string;
          archived_at?: string | null;
        };
        Update: {
          id?: string;
          lead_id?: string | null;
          proposal_id?: string | null;
          company_name?: string;
          contact_name?: string | null;
          contact_email?: string | null;
          sector?: string | null;
          country?: string | null;
          contract_start?: string;
          contract_end?: string;
          monthly_value?: number;
          health_status?: string;
          onboarding_complete?: boolean;
          onboarding_completed_at?: string | null;
          renewal_flagged_90d?: boolean;
          renewal_flagged_30d?: boolean;
          assigned_am_id?: string | null;
          created_at?: string;
          updated_at?: string;
          archived_at?: string | null;
        };
        Relationships: [];
      };
      client_health_history: {
        Row: {
          id: string;
          client_id: string;
          health_status: string;
          product_activity_signal: string | null;
          invoice_status_signal: string | null;
          communication_signal: string | null;
          sentiment_signal: string | null;
          note: string | null;
          recorded_by_agent_id: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          client_id: string;
          health_status: string;
          product_activity_signal?: string | null;
          invoice_status_signal?: string | null;
          communication_signal?: string | null;
          sentiment_signal?: string | null;
          note?: string | null;
          recorded_by_agent_id?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          client_id?: string;
          health_status?: string;
          product_activity_signal?: string | null;
          invoice_status_signal?: string | null;
          communication_signal?: string | null;
          sentiment_signal?: string | null;
          note?: string | null;
          recorded_by_agent_id?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
      invoices: {
        Row: {
          id: string;
          client_id: string;
          invoice_reference: string | null;
          amount: number;
          due_date: string;
          paid_at: string | null;
          status: string;
          overdue_days: number | null;
          flagged: boolean;
          flag_level: string | null;
          flag_note: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          client_id: string;
          invoice_reference?: string | null;
          amount: number;
          due_date: string;
          paid_at?: string | null;
          status?: string;
          overdue_days?: number | null;
          flagged?: boolean;
          flag_level?: string | null;
          flag_note?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          client_id?: string;
          invoice_reference?: string | null;
          amount?: number;
          due_date?: string;
          paid_at?: string | null;
          status?: string;
          overdue_days?: number | null;
          flagged?: boolean;
          flag_level?: string | null;
          flag_note?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      approvals: {
        Row: {
          id: string;
          urgency: string;
          action_summary: string;
          recipient: string | null;
          context: string | null;
          draft_content: string | null;
          risks_if_approved: string | null;
          risks_if_rejected: string | null;
          alternatives: string | null;
          risk_if_delayed: string | null;
          status: string;
          approved_by_user_id: string | null;
          decision_at: string | null;
          discord_message_id: string | null;
          created_by_agent_id: string | null;
          related_entity_type: string | null;
          related_entity_id: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          urgency: string;
          action_summary: string;
          recipient?: string | null;
          context?: string | null;
          draft_content?: string | null;
          risks_if_approved?: string | null;
          risks_if_rejected?: string | null;
          alternatives?: string | null;
          risk_if_delayed?: string | null;
          status?: string;
          approved_by_user_id?: string | null;
          decision_at?: string | null;
          discord_message_id?: string | null;
          created_by_agent_id?: string | null;
          related_entity_type?: string | null;
          related_entity_id?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          urgency?: string;
          action_summary?: string;
          recipient?: string | null;
          context?: string | null;
          draft_content?: string | null;
          risks_if_approved?: string | null;
          risks_if_rejected?: string | null;
          alternatives?: string | null;
          risk_if_delayed?: string | null;
          status?: string;
          approved_by_user_id?: string | null;
          decision_at?: string | null;
          discord_message_id?: string | null;
          created_by_agent_id?: string | null;
          related_entity_type?: string | null;
          related_entity_id?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      deal_learnings: {
        Row: {
          id: string;
          lead_id: string;
          outcome: string;
          icp_match_quality: string | null;
          icp_match_notes: string | null;
          stage_lost_at: string | null;
          deal_velocity_days: number | null;
          velocity_by_stage: Json | null;
          objections: Json | null;
          champion_role: string | null;
          champion_effectiveness: string | null;
          competitor_involved: boolean;
          competitor_name: string | null;
          competitor_win_reason: string | null;
          loss_reason_primary: string | null;
          loss_reason_secondary: string | null;
          loss_type: string | null;
          margin_achieved: number | null;
          key_learning: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          lead_id: string;
          outcome: string;
          icp_match_quality?: string | null;
          icp_match_notes?: string | null;
          stage_lost_at?: string | null;
          deal_velocity_days?: number | null;
          velocity_by_stage?: Json | null;
          objections?: Json | null;
          champion_role?: string | null;
          champion_effectiveness?: string | null;
          competitor_involved?: boolean;
          competitor_name?: string | null;
          competitor_win_reason?: string | null;
          loss_reason_primary?: string | null;
          loss_reason_secondary?: string | null;
          loss_type?: string | null;
          margin_achieved?: number | null;
          key_learning: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          lead_id?: string;
          outcome?: string;
          icp_match_quality?: string | null;
          icp_match_notes?: string | null;
          stage_lost_at?: string | null;
          deal_velocity_days?: number | null;
          velocity_by_stage?: Json | null;
          objections?: Json | null;
          champion_role?: string | null;
          champion_effectiveness?: string | null;
          competitor_involved?: boolean;
          competitor_name?: string | null;
          competitor_win_reason?: string | null;
          loss_reason_primary?: string | null;
          loss_reason_secondary?: string | null;
          loss_type?: string | null;
          margin_achieved?: number | null;
          key_learning?: string;
          created_at?: string;
        };
        Relationships: [];
      };
      onboarding_patterns: {
        Row: {
          id: string;
          client_id: string;
          health_at_day30: string;
          time_to_value_days: number | null;
          friction_points: Json | null;
          escalations: number;
          day7_signals: string | null;
          key_learning: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          client_id: string;
          health_at_day30: string;
          time_to_value_days?: number | null;
          friction_points?: Json | null;
          escalations?: number;
          day7_signals?: string | null;
          key_learning: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          client_id?: string;
          health_at_day30?: string;
          time_to_value_days?: number | null;
          friction_points?: Json | null;
          escalations?: number;
          day7_signals?: string | null;
          key_learning?: string;
          created_at?: string;
        };
        Relationships: [];
      };
      heartbeats: {
        Row: {
          id: string;
          job_name: string;
          scheduled_at: string;
          fired_at: string;
          status: string;
          summary: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          job_name: string;
          scheduled_at: string;
          fired_at: string;
          status: string;
          summary?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          job_name?: string;
          scheduled_at?: string;
          fired_at?: string;
          status?: string;
          summary?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
    };
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: Record<string, never>;
    CompositeTypes: Record<string, never>;
  };
}
