import { createClient } from "@/lib/supabase/server";
import { ReportsClient } from "./_components/reports-client";

export default async function ReportsPage() {
  const supabase = await createClient();

  const { data: reports } = await supabase
    .from("weekly_reports")
    .select("*")
    .order("week_start", { ascending: false })
    .limit(52);

  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-2xl font-semibold text-zinc-50">
          Weekly Reports
        </h1>
        <p className="text-sm text-zinc-400">
          {reports?.length ?? 0} reports generated by HERMES
        </p>
      </div>
      <ReportsClient reports={reports ?? []} />
    </div>
  );
}
