import { createClient } from "@/lib/supabase/server";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { format, formatDistanceToNow } from "date-fns";

export default async function StandupPage() {
  const supabase = await createClient();

  const { data: reports } = await supabase
    .from("standup_reports")
    .select("*, agent:generated_by(name, slug)")
    .order("generated_at", { ascending: false })
    .limit(30);

  const items = reports ?? [];

  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-2xl font-semibold text-zinc-50">Standup Reports</h1>
        <p className="text-sm text-zinc-400">
          Auto-generated standup summaries
        </p>
      </div>

      {items.length === 0 ? (
        <Card className="border-zinc-800 bg-zinc-900">
          <CardContent className="py-12 text-center text-sm text-zinc-500">
            No standup reports generated yet.
          </CardContent>
        </Card>
      ) : (
        <div className="space-y-4">
          {items.map((r) => {
            const agent = r.agent as unknown as { name: string; slug: string } | null;
            const content = r.content as Record<string, unknown>;
            return (
              <a key={r.id} href={`/standup/${r.id}`}>
                <Card className="border-zinc-800 bg-zinc-900 transition-colors hover:border-zinc-700">
                  <CardHeader className="pb-2">
                    <div className="flex items-center justify-between">
                      <CardTitle className="text-sm font-medium text-zinc-50">
                        {format(new Date(r.period_start), "MMM d")} –{" "}
                        {format(new Date(r.period_end), "MMM d, yyyy")}
                      </CardTitle>
                      <span className="text-xs text-zinc-500">
                        {formatDistanceToNow(new Date(r.generated_at), {
                          addSuffix: true,
                        })}
                      </span>
                    </div>
                  </CardHeader>
                  <CardContent>
                    <div className="flex items-center gap-2 text-xs text-zinc-400">
                      {agent && (
                        <span>Generated by <span className="text-indigo-400">{agent.name}</span></span>
                      )}
                      {content.summary && (
                        <span className="line-clamp-1">
                          – {String(content.summary)}
                        </span>
                      )}
                    </div>
                  </CardContent>
                </Card>
              </a>
            );
          })}
        </div>
      )}
    </div>
  );
}
