import { createClient } from "@/lib/supabase/server";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { notFound } from "next/navigation";
import { format } from "date-fns";

export default async function StandupDetailPage({
  params,
}: {
  params: Promise<{ id: string }>;
}) {
  const { id } = await params;
  const supabase = await createClient();

  const { data: report } = await supabase
    .from("standup_reports")
    .select("*, agent:generated_by(name, slug)")
    .eq("id", id)
    .single();

  if (!report) notFound();

  const agent = report.agent as unknown as { name: string; slug: string } | null;
  const content = report.content as Record<string, unknown>;

  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-2xl font-semibold text-zinc-50">Standup Report</h1>
        <p className="text-sm text-zinc-400">
          {format(new Date(report.period_start), "MMM d")} –{" "}
          {format(new Date(report.period_end), "MMM d, yyyy")}
          {agent && (
            <> · Generated by <span className="text-indigo-400">{agent.name}</span></>
          )}
        </p>
      </div>

      {content.summary && (
        <Card className="border-zinc-800 bg-zinc-900">
          <CardHeader>
            <CardTitle className="text-sm font-medium text-zinc-400">
              Summary
            </CardTitle>
          </CardHeader>
          <CardContent>
            <p className="text-sm text-zinc-200">{String(content.summary)}</p>
          </CardContent>
        </Card>
      )}

      {content.highlights && Array.isArray(content.highlights) && (
        <Card className="border-zinc-800 bg-zinc-900">
          <CardHeader>
            <CardTitle className="text-sm font-medium text-zinc-400">
              Highlights
            </CardTitle>
          </CardHeader>
          <CardContent>
            <ul className="space-y-1.5">
              {content.highlights.map((h: unknown, i: number) => (
                <li key={i} className="text-sm text-zinc-300">
                  • {String(h)}
                </li>
              ))}
            </ul>
          </CardContent>
        </Card>
      )}

      {content.blockers && Array.isArray(content.blockers) && content.blockers.length > 0 && (
        <Card className="border-red-800/50 bg-zinc-900">
          <CardHeader>
            <CardTitle className="text-sm font-medium text-red-400">
              Blockers
            </CardTitle>
          </CardHeader>
          <CardContent>
            <ul className="space-y-1.5">
              {content.blockers.map((b: unknown, i: number) => (
                <li key={i} className="text-sm text-zinc-300">
                  • {String(b)}
                </li>
              ))}
            </ul>
          </CardContent>
        </Card>
      )}

      <Card className="border-zinc-800 bg-zinc-900">
        <CardHeader>
          <CardTitle className="text-sm font-medium text-zinc-400">
            Raw Data
          </CardTitle>
        </CardHeader>
        <CardContent>
          <pre className="overflow-x-auto text-xs text-zinc-300">
            {JSON.stringify(content, null, 2)}
          </pre>
        </CardContent>
      </Card>
    </div>
  );
}
